### ISSUE TITLE
Segmentation fault error on zsh

### ISSUE THREAD

**Issue by michaelseibt** [heapwolf/prompt-sync#24]
Hi there!

Coming from [Nucleus](https://github.com/holidaypirates/nucleus/), one of the users reported a problem with our `init` script.

While prompting for user input, the script terminates with a seg-fault if the user tries to resize the terminal window.

`[1] 3380 segmentation fault nucleus init`

I know that this could be a problem with zsh, since the error seems to be on a quite low level.

Steps to reproduce:
- Open a terminal window with zsh (I tested this on MacOS with iTerm and zsh) and navigate to the prompt-sync repository root.
- Run `node test.js` and resize the window during the first prompt.

**Comment by davidmarkclements** [comment]
there's nothing that this module is doing that would (or at least should) cause a segfault - 
it's either a zsh issue (most likely) or a node core issue. Closing as this isn't a problem with this module
