### ISSUE TITLE
process.stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by Gibolt** [heapwolf/prompt-sync#26]
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: process.stdin.setRawMode is not a function
    at prompt (C:\Git\LiveTranslate\node_modules\prompt-sync\index.js:66:34)

This can be fixed by ignoring setRawMode for non-TTY consoles

**Comment by VictorVuSon** [comment]
How did you ignore setRawMode for non-TTY consoles on ubuntu..Please let me know.

**Comment by 0x00A** [comment]
👍 

PR welcome :)

**Comment by FMGordillo** [comment]
Sorry, how did you solve this issue? I am using PowerShell and CMD, and both gave that issue.

**Comment by boltex** [comment]
I get this error while using on windows in git-bash
